name: a57-tp-action
on: [push]
jobs:
  train:
    runs-on: [self-hosted, cml]
    steps:
      - uses: actions/checkout@v2
      - name: Setting up the environment
        run: |
          pip install -r requirements.txt
      - name: Setting up DVC
        run: |
          dvc init
          dvc remote add -d tp-a57-dvc s3://tp-a57/model/
          dvc remote modify tp-a57-dvc endpointurl https://minio.cyber.monster:9000
          dvc remote modify tp-a57-dvc access_key_id tp-hafed
          dvc remote modify tp-a57-dvc secret_access_key strong-password
          dvc pull
      - name: Training the model
        run: |
          python rl_tp.py
      - name: Pushing new training data to DVC
        run: |
          dvc add data.csv
      - name: Pushing new model to DVC
        run: |
          dvc add model.dat
          dvc push
      - name: Sending report
        run: |
          echo >> report.md
          echo '## model.dat.dvc' >> report.md
          cat model.dat.dvc >> report.md
          echo >> report.md
          echo '## data.csv.dvc' >> report.md
          cat data.csv.dvc >> report.md
          cml send-comment report.md
