name: a57-tp-action
on: [push]
jobs:
  train:
    runs-on: [self-hosted, cml]
    steps:
      - uses: actions/checkout@v2
      - name: Setting up the environment
        run: |
          pip install -r requirements.txt 
      - name: Training the model
        run: |
          python rl_tp.py
          date > date.txt
          cml pr --auto-merge date.txt
      - name: Sending report
        run: |
          cml send-comment report.md